### ISSUE TITLE
build error from thud, rocko, sumo,warrior for MACHINE=zcu102-zynqmp

### ISSUE THREAD

**Issue by noelpedro** [carlesfernandez/oe-gnss-sdr-manifest#1]
Hey guys I'm getting build errors when attempting to build for my zynqMP target machine.

**Comment by carlesfernandez** [comment]
Haven't tried that one. Could you post the errors you are getting?

**Comment by noelpedro** [comment]
This is the Thud error for both ubunutu 18.04 and ubuntu 16.04:

ERROR: u-boot-xlnx-v2018.01-xilinx-v2018.3+gitAUTOINC+d8fc4b3b70-r0 do_compile: oe_runmake failed
ERROR: u-boot-xlnx-v2018.01-xilinx-v2018.3+gitAUTOINC+d8fc4b3b70-r0 do_compile: Function failed: do_compile

**Comment by noelpedro** [comment]
This is one of the errors, well first its a warning but later in the compilation it becomes an error.

WARNING: /home/user/work/arm64-cross-compile/oe-repo/oe-core/../meta-gnss-sdr/recipes-support/hdf5/hdf5_1.8.15.1.bb: Unable to get checksum for hdf5 SRC_URI entry H5Tinit.c: file could not be found
WARNING: /home/user/work/arm64-cross-compile/oe-repo/oe-core/../meta-gnss-sdr/recipes-support/hdf5/hdf5_1.8.15.1.bb: Unable to get checksum for hdf5 SRC_URI entry H5lib_settings.c: file could not be found


It looks for hdf5 in the wrong directory i move the respective aarch64 hdf5 files to to parent directory and this solves this problem. I'll post more on the other error soon.



thanks.

**Comment by noelpedro** [comment]
GO this unexpected error form armadillo libraries. 

`WARNING: armadillo-9.860.x-r0 do_fetch: Failed to fetch URL git://gitlab.com/conradsnicta/armadillo-code.git;branch=9.860.x;protocol=https, attempting MIRRORS if available
ERROR: armadillo-9.860.x-r0 do_fetch: Fetcher failure: Unable to find revision 529118967b5287bab411c7c27cbb9ecaab218c6d in branch 9.860.x even from upstream
ERROR: armadillo-9.860.x-r0 do_fetch: Fetcher failure for URL: 'git://gitlab.com/conradsnicta/armadillo-code.git;branch=9.860.x;protocol=https'. Unable to fetch URL from any source.
ERROR: armadillo-9.860.x-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/user/work/arm64-cross-compile/oe-repo/build/tmp-glibc/work/aarch64-oe-linux/armadillo/9.860.x-r0/temp/log.do_fetch.10936
ERROR: Task (/home/user/work/arm64-cross-compile/oe-repo/oe-core/../meta-gnss-sdr/recipes-core/armadillo/armadillo_9.860.x.bb:do_fetch) failed with exit code '1'
`

**Comment by noelpedro** [comment]
Rocko error:

ERROR: Task (/home/user/work/arm64-cross-compile/oe-repo/oe-core/meta/recipes-devtools/m4/m4-native_1.4.18.bb:do_compile) failed with exit code '


attempting sumo now
