### ISSUE TITLE
error fetching armadillo

### ISSUE THREAD

**Issue by Abdob** [carlesfernandez/oe-gnss-sdr-manifest#2]
I'm getting this error:
ERROR: armadillo-9.900.x-r0 do_fetch: Fetcher failure: Unable to find revision 31743403deee1f333fed91cde4f59f5403552e28 in branch 9.900.x even from upstream

When I run:
bitbake gnss-sdr-dev-image

**Comment by carlesfernandez** [comment]
Thanks for spotting this issue. It's now fixed in all branches.

**Comment by Abdob** [comment]
Thanks, I believe it is passed this point. I haven't been able to build because my quad core cpu keeps freezing from the processing load. I haven't managed to limit the number of threads. I will try compiling with a stronger system next week.
