### ISSUE TITLE
qt5base failed compilation

### ISSUE THREAD

**Issue by Abdob** [carlesfernandez/oe-gnss-sdr-manifest#3]
This is what I get with running the instructions as is (default machine).

| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/wave/sdr/gnss-sdr/oe-repo/build/tmp-glibc/work/armv7ahf-neon-oe-linux-gnueabi/qtbase/5.11.3+gitAUTOINC+08de243eaa-r0/temp/log.do_compile.1496)
ERROR: Task (/home/wave/sdr/gnss-sdr/oe-repo/oe-core/../meta-qt5/recipes-qt/qt5/qtbase_git.bb:do_compile) failed with exit code '1'

**Comment by carlesfernandez** [comment]
What branch are you using?
