### ISSUE TITLE
fpga command keeps failing in uboot

### ISSUE THREAD

**Issue by gisellegk** [carlesfernandez/oe-gnss-sdr-manifest#4]
I am trying to boot the gnss-sdr-dev-image on my zedboard. However, I keep getting this usage message on the fpga command. 

`fpga ${bitstream_type} 0 ${bitstream_load_address} ${filesize}`
where 
```
bitstream_type=load
bitstream_load_address=0x100000
filesize=1548C
```
I notice that filesize matches the number of bytes of the file read when the bitstream is loaded, although it doesn't have 0x in front. I tried rerunning the same command from u-boot by typing 0x1548C manually and hard coding the value but still get the same result.

![image](https://user-images.githubusercontent.com/3026367/89433959-322cf380-d700-11ea-8a32-d89d04108a47.png)

**Comment by carlesfernandez** [comment]
I hope you get that working. I'm closing this issue since it seems not related to this repository.
